[tool.poetry]
name = "dice-be"
version = "0.1.0"
description = "Backend for Dice Game"
authors = [
    "Koren Minchev <korenminchev@gmail.com>",
    "Michael Shustin <michaelshustin@gmail.com>",
]

[tool.poetry.dependencies]
python = "^3.12"
odmantic = "^0.9"
uvicorn = {extras = ["standard"], version = "^0.19.0"}
bidict = "^0.22.0"
pydantic = "^1.10.2"
loguru = "^0.6.0"
fastapi = {version = ">=0.99,<1.0", extras = ["all"]}

[tool.poetry.group.dev.dependencies]
pylint = "^2.15.5"
pytest = "^7.2.0"
httpx = "^0.25.0"
requests = "^2.31.0"
anyio = "<4"

[tool.pylint]
    [tool.pylint.'FORMAT']
    max-line-length=120

    [tool.pylint.'MESSAGES CONTROL']
    extension-pkg-whitelist = "pydantic"

[tool.ruff]
line-length = 120

[tool.black]
target-version = ['py311']
skip-string-normalization = true

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
